CREATE TABLE flow_contexts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  telegram_first_name VARCHAR(255),
  current_step VARCHAR(64) NOT NULL,
  flow_type VARCHAR(64) NOT NULL,
  user_name VARCHAR(255),
  age INT,
  phone VARCHAR(64),
  reading_level VARCHAR(64),
  consent_given BOOLEAN NOT NULL DEFAULT FALSE,
  school_channel_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
  referrer_user_id BIGINT NOT NULL DEFAULT 0,
  referral_entry_source VARCHAR(64),
  referral_entry_at TIMESTAMP,
  temp_tags VARCHAR(2000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE flow_contexts
  ADD CONSTRAINT uq_flow_contexts_user_id UNIQUE (user_id);
