CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  telegram_first_name VARCHAR(255),
  user_name VARCHAR(255),
  age INT,
  phone VARCHAR(64),
  reading_level VARCHAR(64),
  is_school_channel_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
  is_course_channel_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
  consent_given BOOLEAN NOT NULL DEFAULT FALSE,
  registration_completed BOOLEAN NOT NULL DEFAULT FALSE,
  registration_completed_at TIMESTAMP NOT NULL,
  referrer_user_id BIGINT NOT NULL DEFAULT 0,
  referral_status VARCHAR(32) NOT NULL,
  referral_counted_at TIMESTAMP NOT NULL,
  referral_points INT NOT NULL DEFAULT 0,
  referral_link_cp VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
  ADD CONSTRAINT uq_users_user_id UNIQUE (user_id);
